main: me.cjCommands.main.Main
name: CJCommands
author: CJM
version: 1.5
api-version: 1.18
description: Random Commands

commands:
   c:
      usage: /<C> [command]
      description: teleports player to a random location